services:
  mysql-dev:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devword