flowchart TD
    build("MODEL build(ResultSet)") -->|Find columns| memberfication{"What is member?"}
    memberfication -->|collection| combine("combine")
    memberfication -->|part of entity| getBuilder("get_BuilderService")
    getBuilder --> complete("complete")
    memberfication -->|else| setField("set(Field, Entry)")
    combine --> anyMembersLeft{"Any members left?"}
    setField --> anyMembersLeft
    complete --> anyMembersLeft
    anyMembersLeft -->|Yes| memberfication
    anyMembersLeft -->|No| findConstructor("Find constructor")
    findConstructor --> constructorState{"Constructor state"}
    constructorState -->|No constructor found| throwBuilderException(("Throw builder exception"))
    constructorState -->|Not correct amount of parameters| throwBuilderException
    constructorState -->|More than one annotated constructor| throwBuilderException
    constructorState -->|Is constructor not public?| throwBuilderException
    constructorState -->|Accepted| getConstructorParameters("Get parameters for constructor")
    getConstructorParameters -->|Sort fields for parameters and get values| fieldsPrepared("Fields are prepared")
    fieldsPrepared --> constructModel{"Build fields from constructor"}
    constructModel -->|Success| return(("return"))
    constructModel -->|Couldn't initiate constructor| constructorBuildFailure(("Throw exception"))
    constructModel -->|Couldn't access constructor| constructorBuildFailure
    constructModel -->|Couldn't invocate target| constructorBuildFailure